<?php

namespace AppBundle\Repository;

/**
 * pointageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pointageRepository extends \Doctrine\ORM\EntityRepository
{
}
